### ISSUE TITLE
Add MkDocs with mkdocstrings for Automated API Documentation

### ISSUE THREAD

**Issue by carpenike** [carpenike/rvc2api#13]
## Summary
Implement MkDocs with mkdocstrings to automatically generate documentation from docstrings in our codebase.

## Motivation
As our FastAPI application grows, maintaining accurate and up-to-date documentation becomes increasingly challenging. Automatically generating documentation from our docstrings would ensure that our documentation stays in sync with our code.

### Tools to Add
- **MkDocs**: Documentation static site generator
- **mkdocstrings**: Plugin for auto-generating API documentation from docstrings
- **material for mkdocs**: Theme with modern look and feel

### Suggested Configuration
```yaml
# mkdocs.yml
site_name: RVC2API Documentation
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
```

### Expected Directory Structure
```
docs/
  index.md
  api/
    core_daemon.md
    rvc_decoder.md
  user-guides/
    installation.md
    configuration.md
```

## Benefits
1. **Consistency**: Documentation stays in sync with code
2. **Accessibility**: Improved developer experience with searchable docs
3. **Onboarding**: Easier for new contributors to understand the codebase
4. **API Reference**: Automatically documents FastAPI endpoints and Pydantic models

## Resources & References
- [MkDocs](https://www.mkdocs.org/)
- [mkdocstrings](https://mkdocstrings.github.io/)
- [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)
- [Example FastAPI + mkdocstrings integration](https://fastapi.tiangolo.com/advanced/extending-openapi/)

## Tasks
- [ ] Add MkDocs and plugins to project dependencies
- [ ] Create initial mkdocs.yml configuration
- [ ] Set up basic documentation structure
- [ ] Ensure existing docstrings follow a consistent format
- [ ] Integrate with CI/CD for automated builds
- [ ] Add task in VS Code for local documentation preview
