### ISSUE TITLE
Add Security Scanning with pip-audit

### ISSUE THREAD

**Issue by carpenike** [carpenike/rvc2api#15]
## Summary
Add `pip-audit` to automatically scan Python dependencies for known security vulnerabilities.

## Motivation
As our project grows and relies on various third-party dependencies, ensuring these dependencies are free from known security vulnerabilities becomes critical. Automated scanning can help us identify and address security issues before they affect production systems.

### Tool to Add
[pip-audit](https://pypi.org/project/pip-audit/) is a tool for scanning Python environments and projects for packages with known vulnerabilities. It leverages the Python Packaging Advisory Database (PyPA) and OSV database to identify packages with security issues.

### Integration Points
1. **Pre-commit hook**: Run lightweight scans before commits
2. **CI/CD Pipeline**: Run comprehensive scans during build processes
3. **Development environment**: Allow manual scans 
4. **Scheduled scans**: Regularly check for new vulnerabilities in existing dependencies

#### Add to development dependencies
```toml
# pyproject.toml
[tool.poetry.group.dev.dependencies]
pip-audit = "^1.0.0"  # Use latest version
```

#### Add to pre-commit config
```yaml
# .pre-commit-config.yaml
  - repo: https://github.com/pypa/pip-audit
    rev: v1.0.0
    hooks:
      - id: pip-audit
        args: ["--requirement", "poetry.lock"]
```

#### Create a VS Code task
```json
{
  "label": "Security Scan (pip-audit)",
  "type": "shell",
  "command": "cd ${workspaceFolder} && poetry run pip-audit",
  "group": "test"
}
```

#### GitHub Action workflow
```yaml
name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run security scan
        run: |
          poetry run pip-audit
```

## Benefits
1. **Early Detection**: Find vulnerabilities before they become problems
2. **Automatic Updates**: Stay informed of newly discovered vulnerabilities
3. **Dependency Management**: Better understanding of dependency risks
4. **Compliance**: Meet security requirements for production systems
5. **Documentation**: Generate reports of security posture

## Resources & References
- [pip-audit Documentation](https://pypi.org/project/pip-audit/)
- [Python Packaging Advisory Database](https://github.com/pypa/advisory-database)
- [OSV (Open Source Vulnerabilities) Database](https://osv.dev/)
- [OWASP Dependency Check Guide](https://owasp.org/www-project-dependency-check/)

## Tasks
- [ ] Add pip-audit to development dependencies
- [ ] Create documentation for usage and interpretation
- [ ] Set up pre-commit integration
- [ ] Configure GitHub Actions workflow for scheduled scans
- [ ] Create VS Code task for manual scanning
- [ ] Document remediation process for when vulnerabilities are found
