### ISSUE TITLE
Implement Frontend Testing with Cypress

### ISSUE THREAD

**Issue by carpenike** [carpenike/rvc2api#16]
## Summary
Add Cypress for end-to-end and integration testing of the React frontend, ensuring robust functionality across the UI layer and its interactions with the FastAPI backend.

## Motivation
While our backend has test coverage, the frontend React application lacks automated testing. Adding comprehensive frontend testing will:
1. Catch regressions during UI changes
2. Verify that frontend components interact properly with the backend
3. Ensure a consistent user experience across browsers
4. Provide confidence when refactoring or adding new features

### Tool to Add
[Cypress](https://www.cypress.io/) is a modern end-to-end testing framework with these advantages:
- Real-time reloading
- Time travel debugging
- Automatic waiting
- Network traffic control
- Consistent results
- Screenshots and videos of tests

#### 1. Add Cypress to the project
```bash
cd web_ui
npm install --save-dev cypress @testing-library/cypress
```

#### 2. Initialize Cypress
```bash
npx cypress open
```

#### 3. Configure TypeScript support
```json
// cypress/tsconfig.json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "@testing-library/cypress"],
    "isolatedModules": false
  },
  "include": [
    "../node_modules/cypress",
    "./**/*.ts"
  ]
}
```

#### 4. Create example test
```typescript
// cypress/e2e/dashboard.cy.ts
describe('Dashboard', () => {
  beforeEach(() => {
    // Set up any test data or state
    cy.intercept('GET', '/api/v1/entities', { fixture: 'entities.json' }).as('getEntities');
    cy.visit('/dashboard');
  });

  it('should display entity cards', () => {
    cy.wait('@getEntities');
    cy.findByTestId('entity-list').should('exist');
    cy.findAllByTestId('entity-card').should('have.length.greaterThan', 0);
  });

  it('should allow filtering entities', () => {
    cy.wait('@getEntities');
    cy.findByPlaceholderText('Filter entities').type('Temperature');
    cy.findAllByTestId('entity-card').should('have.length', 2);
  });

  // More test cases...
});
```

#### GitHub Actions Workflow
```yaml
name: Frontend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'web_ui/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'web_ui/**'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: |
          cd web_ui
          npm ci
          
      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          working-directory: web_ui
          build: npm run build
          start: npm run preview
          wait-on: 'http://localhost:4173'
          browser: chrome
```

### Testing Strategy

1. **Unit Tests**:
   - Individual React components
   - Helper functions and hooks
   - State management

2. **Integration Tests**:
   - Component interactions
   - Form submissions
   - State changes across components

3. **End-to-End Tests**:
   - Critical user flows
   - Navigation between pages
   - API interactions

### VS Code Tasks

```json
{
  "label": "Cypress Open",
  "type": "shell",
  "command": "cd ${workspaceFolder}/web_ui && npx cypress open",
  "group": "test"
},
{
  "label": "Cypress Run Tests",
  "type": "shell",
  "command": "cd ${workspaceFolder}/web_ui && npx cypress run",
  "group": "test"
}
```

## Benefits

1. **Confidence in Changes**: Make frontend changes with assurance that existing functionality remains intact
2. **Documentation**: Tests serve as living documentation of expected behavior
3. **Faster Development**: Catch issues early in the development process
4. **Browser Compatibility**: Verify functionality across different browsers
5. **Reduced Manual Testing**: Automate repetitive test cases

## Resources & References

- [Cypress Documentation](https://docs.cypress.io/)
- [Testing Library with Cypress](https://testing-library.com/docs/cypress-testing-library/intro/)
- [React Testing Best Practices](https://testing-library.com/docs/react-testing-library/intro/)
- [GitHub Actions for Cypress](https://github.com/cypress-io/github-action)

## Tasks

- [ ] Install Cypress and dependencies
- [ ] Configure TypeScript support
- [ ] Set up test fixtures and utilities
- [ ] Create tests for critical components
- [ ] Add end-to-end tests for main user flows
- [ ] Configure GitHub Actions workflow
- [ ] Add VS Code tasks
- [ ] Document testing strategy and patterns
- [ ] Include test coverage reporting
