### ISSUE TITLE
Add pytest-cov for Code Coverage Reporting

### ISSUE THREAD

**Issue by carpenike** [carpenike/rvc2api#18]
## Summary
Add pytest-cov to the project to track and report test coverage for Python code, helping identify areas needing additional testing.

## Motivation
While the project has good test coverage in some areas, we don't currently have visibility into which parts of the codebase are well-tested and which parts lack coverage. Adding code coverage reporting would help:

1. Identify untested or undertested code
2. Ensure critical components have sufficient test coverage
3. Track coverage metrics over time
4. Provide confidence when making changes
5. Encourage test-driven development

### Tool to Add
[pytest-cov](https://github.com/pytest-dev/pytest-cov) is a plugin for pytest that integrates with the coverage.py library to measure code coverage during test execution.

### Setup Process

1. **Add pytest-cov to development dependencies**:
```toml
# pyproject.toml
[tool.poetry.group.dev.dependencies]
pytest-cov = "^4.1.0"  # Use the latest version
```

2. **Configure coverage settings**:
```toml
# pyproject.toml
[tool.coverage.run]
source = ["src"]
omit = ["tests/*", "*/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError",
]
```

3. **Create a VS Code task**:
```json
{
  "label": "Run Tests with Coverage",
  "type": "shell",
  "command": "cd ${workspaceFolder} && poetry run pytest --cov=src --cov-report=xml --cov-report=term",
  "group": "test"
}
```

4. **Configure GitHub Actions** to run tests with coverage:
```yaml
# Add to existing Python test workflow
- name: Run tests with coverage
  run: poetry run pytest --cov=src --cov-report=xml
  
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v3
  with:
    file: ./coverage.xml
    fail_ci_if_error: false
```

### Coverage Reporting Options

1. **Terminal output**: Basic coverage statistics in the console
```
$ poetry run pytest --cov=src
```

2. **HTML reports**: Interactive HTML report showing covered/uncovered lines
```
$ poetry run pytest --cov=src --cov-report=html
```

3. **XML reports**: For CI integration (e.g., with Codecov)
```
$ poetry run pytest --cov=src --cov-report=xml
```

4. **Coverage badges**: Add a coverage badge to README.md

### Pre-commit Integration (Optional)
```yaml
# .pre-commit-config.yaml
- repo: local
  hooks:
    - id: pytest-check
      name: pytest with coverage
      entry: poetry run pytest --cov=src --cov-report=term --cov-fail-under=80
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
```

## Benefits

1. **Visibility**: Clear metrics on which parts of the code are tested
2. **Quality Assurance**: Identify critical components needing better test coverage
3. **Confidence**: Greater confidence when refactoring or adding features
4. **Documentation**: Coverage reports help understand code behavior
5. **Motivation**: Encourage writing tests for uncovered code

## Resources & References

- [pytest-cov Documentation](https://pytest-cov.readthedocs.io/en/latest/)
- [coverage.py Documentation](https://coverage.readthedocs.io/)
- [Codecov Integration](https://about.codecov.io/)
- [Test Coverage Best Practices](https://martinfowler.com/bliki/TestCoverage.html)

## Tasks

- [ ] Add pytest-cov to development dependencies
- [ ] Configure coverage settings in pyproject.toml
- [ ] Add VS Code tasks for running tests with coverage
- [ ] Configure CI to run and report coverage metrics
- [ ] Decide on coverage goals and thresholds
- [ ] (Optional) Add coverage badge to README.md
- [ ] Document coverage analysis workflow
