### ISSUE TITLE
DevContainer: Set Up CI/CD for Container Image Building

### ISSUE THREAD

**Issue by carpenike** [carpenike/rvc2api#43]
## Problem

Currently, each developer must build the devcontainer image locally, which is time-consuming and may lead to inconsistencies in development environments. There's no automated process to ensure the devcontainer image is built and available when needed.

## Solution

Implement a GitHub Actions workflow to automatically build and publish the devcontainer image:

1. Create a GitHub Actions workflow that builds the devcontainer image
2. Publish the built image to GitHub Container Registry (GHCR)
3. Configure the devcontainer.json to use the pre-built image
4. Set up versioning for the container image

## Implementation Details

Create a GitHub Actions workflow in `.github/workflows/build-devcontainer.yml`:

```yaml
name: Build and Publish DevContainer

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/devcontainer:latest
            ghcr.io/${{ github.repository }}/devcontainer:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

Update devcontainer.json to use the pre-built image:

```json
{
  "name": "RVC2API Nix Development",
  "image": "ghcr.io/carpenike/rvc2api/devcontainer:latest",
  // Other settings...
}
```

## Benefits

- **Faster Development Setup**: New developers can use pre-built images
- **Consistency**: All developers use the exact same environment
- **Reduced Resource Usage**: Less building on developer machines
- **Versioned Environments**: Tag images with project versions for reproducible environments
- **CI Integration**: The image building process becomes part of the CI/CD pipeline

## References

- [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
- [Docker Build and Push Action](https://github.com/docker/build-push-action)
- [VS Code Pre-built Container Images](https://code.visualstudio.com/remote/advancedcontainers/prebuilt-images)
