### ISSUE TITLE
Implement CI/CD Pipeline for DevContainer Image Building

### ISSUE THREAD

**Issue by carpenike** [carpenike/rvc2api#47]
## Problem Statement
The development container is currently built locally for each developer, leading to potentially long setup times for new contributors and inconsistent development environments. Without a pre-built container image, every developer must wait for the full container build process when starting the project for the first time or when significant changes are made to the devcontainer configuration.

## Proposed Solution
Set up a GitHub Actions workflow to automatically build, version, and publish the development container image to GitHub Container Registry (GHCR) whenever changes are made to the `.devcontainer` directory or related configuration files.

### Implementation Details
1. Create a GitHub Actions workflow file at `.github/workflows/build-devcontainer.yml`:
   ```yaml
   name: Build DevContainer Image

   on:
     push:
       branches: [main]
       paths:
         - '.devcontainer/**'
         - '.github/workflows/build-devcontainer.yml'
     pull_request:
       paths:
         - '.devcontainer/**'
         - '.github/workflows/build-devcontainer.yml'
     workflow_dispatch:  # Allow manual triggers

   jobs:
     build:
       runs-on: ubuntu-latest
       permissions:
         contents: read
         packages: write
         
       steps:
         - name: Checkout
           uses: actions/checkout@v3
           
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2
           
         - name: Login to GitHub Container Registry
           uses: docker/login-action@v2
           with:
             registry: ghcr.io
             username: ${{ github.actor }}
             password: ${{ secrets.GITHUB_TOKEN }}
             
         - name: Extract metadata
           id: meta
           uses: docker/metadata-action@v4
           with:
             images: ghcr.io/${{ github.repository }}/devcontainer
             tags: |
               type=sha,prefix=
               type=ref,event=branch
               type=semver,pattern={{version}}
               latest
               
         - name: Build and push
           uses: docker/build-push-action@v4
           with:
             context: .devcontainer
             file: .devcontainer/Dockerfile
             push: ${{ github.event_name != 'pull_request' }}
             tags: ${{ steps.meta.outputs.tags }}
             labels: ${{ steps.meta.outputs.labels }}
             cache-from: type=gha
             cache-to: type=gha,mode=max
   ```

2. Update the `devcontainer.json` to use the pre-built image:
   ```json
   {
     "name": "RVC2API Nix Development",
     "image": "ghcr.io/carpenike/rvc2api/devcontainer:latest",
     // If the image doesn't exist or the user wants to build locally:
     "build": {
       "dockerfile": "Dockerfile",
       "context": "."
     }
   }
   ```

3. Add documentation in `docs/devcontainer-ci.md` explaining the CI process and how to use the pre-built image.

## Benefits
- **Faster Onboarding**: New contributors can immediately use a pre-built container
- **Consistent Development Environments**: Everyone uses the exact same container image
- **Reduced Resource Usage**: GitHub Actions handles compute-intensive builds
- **Version Control**: Container images are versioned and can be referenced by specific tags
- **Automatic Updates**: Container is rebuilt whenever configuration changes

## Research
- GitHub Actions provides free compute resources for building container images
- GitHub Container Registry can host container images for free for public repositories
- VS Code's devcontainer.json supports both direct image references and local builds
- Docker layer caching in GitHub Actions significantly speeds up repeat builds

## Related Documentation
- [GitHub Actions: Docker build & push](https://github.com/marketplace/actions/build-and-push-docker-images)
- [VS Code Dev Containers: Pre-built images](https://code.visualstudio.com/docs/remote/containers#_prebuilding-images)
- [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
