### ISSUE TITLE
Improve documentation CI/CD with automated builds, validation, and preview deployments

### ISSUE THREAD

**Issue by carpenike** [carpenike/rvc2api#52]
## Problem Statement

Our documentation CI/CD pipeline could be improved to automatically build, validate, and deploy versioned documentation. Currently, documentation deployment requires manual steps and lacks automatic preview deployments for pull requests.

## Proposed Solution

Set up a comprehensive CI/CD workflow for documentation that includes:

1. Automatic build and deployment of documentation on each release
2. Deployment of "dev" version when changes are pushed to the main branch
3. Documentation preview deployments for pull requests
4. Documentation validation (linting, broken links checking) in the CI pipeline

## Implementation Tasks

- [ ] Create a GitHub Actions workflow for documentation build and deployment
  ```yaml
  name: docs
  on:
    push:
      branches:
        - main
      tags:
        - 'v*'
    pull_request:
      paths:
        - 'docs/**'
        - 'mkdocs.yml'
        - '.github/workflows/docs.yml'
  ```
- [ ] Add a documentation validation step that checks for:
  - Broken internal links
  - Markdown linting issues
  - OpenAPI schema validity
- [ ] Configure automatic versioning with mike for tagged releases
- [ ] Set up preview deployments for documentation changes in PRs
- [ ] Add documentation status badges to README.md

## Benefits

- Ensures documentation is always up-to-date with the latest code
- Provides preview environments for reviewing documentation changes
- Catches documentation issues before they reach users
- Automates the versioning process
- Follows DevOps best practices for documentation

## References

- [MkDocs deployment with GitHub Actions](https://github.com/mhausenblas/mkdocs-deploy-gh-pages)
- [Mike documentation for versioning](https://github.com/jimporter/mike)
- [Example documentation CI/CD in popular projects](https://fastapi.tiangolo.com/contributing/)
